export const USER_PLAYLIST="USER_PLAYLIST";//用户的歌单
export const COLLECT = "COLLECT"//收藏
export const COLLECT_ALBUM = "COLLECT_ALBUM"//收藏的专辑
export const COLLECT_SINGER = "COLLECT_SINGER"//收藏歌单
export const COLLECT_VIDEO ="COLLECT_VIDEO"//收藏视频
export const RECOMMEND_CONTENT ="RECOMMEND_CONTENT"//推荐专辑
export const SINGER_RECOMMEND ="SINGER_RECOMMEND"//推荐歌手
export const RECOMMEND_RADIO ="RECOMMEND_RADIO"//推荐电台
export const SUBSCRIBE ="SUBSCRIBE"//订阅电台
export const REAENT_SONGS ="REAENT_SONGS"//最近播放音乐