export const UP_RADIORECOMEENDIST = "UP_RADIORECOMEENDIST";
export const UP_CONCENTRATELIST = "UP_CONCENTRATELIST";
export const UP_POPULARLIST = "UP_POPULARLIST";
export const UP_RSBANNER_LIST = "UP_RSBANNER_LIST";
export const UP_SORTLIST = "UP_SORTLIST";
export const UP_PAYMENTLIST = "UP_PAYMENTLIST";
export const UP_CLASSINFOLIST = "UP_CLASSINFOLIST";
export const UP_MP3 = "UP_MP3";
export const UP_PLAYLIST = "UP_PLAYLIST";
export const UP_MUSICURL = "UP_MUSICURL";
export const UP_PROGRAMLIST = "UP_PROGRAMLIST";
export const CHANGE_IS_LOADING = "CHANGE_IS_LOADING"
export const UP_RADIODJDETAIL = "UP_RADIODJDETAIL";
export const UP_RADIODJPROGRAM = "UP_RADIODJPROGRAM";

