export const UP_RADIORECOMEENDIST = "UP_RADIORECOMEENDIST";
export const UP_CONCENTRATELIST = "UP_CONCENTRATELIST";
export const UP_POPULARLIST = "UP_POPULARLIST";
export const UP_RSBANNER_LIST = "UP_RSBANNER_LIST";
export const UP_SORTLIST = "UP_SORTLIST";
export const UP_PAYMENTLIST = "UP_PAYMENTLIST";
